<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC4155" name="com.cure.softweb.RUN.HomePage" tests="8" failures="0" timestamp="30 Jun 2017 09:56:22 GMT" time="96.188" errors="1">
  <testcase name="createsp4" time="14.268" classname="com.cure.softweb.RUN.HomePage"/>
  <testcase name="createsp6" time="11.752" classname="com.cure.softweb.RUN.HomePage"/>
  <testcase name="login" time="14.442" classname="com.cure.softweb.RUN.HomePage">
    <error type="java.io.IOException" message="The system cannot find the path specified">
      <![CDATA[java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at customreports.Reports.updateResult(Reports.java:34)
	at com.cure.softweb.RUN.HomePage.login(HomePage.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- login -->
  <testcase name="createsp7" time="7.178" classname="com.cure.softweb.RUN.HomePage"/>
  <testcase name="createsp2" time="1.905" classname="com.cure.softweb.RUN.HomePage"/>
  <testcase name="createsp3" time="3.409" classname="com.cure.softweb.RUN.HomePage"/>
  <testcase name="createsp5" time="10.744" classname="com.cure.softweb.RUN.HomePage"/>
  <testcase name="createsp1" time="32.490" classname="com.cure.softweb.RUN.HomePage"/>
</testsuite> <!-- com.cure.softweb.RUN.HomePage -->
